config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :rails_method_descriptions
  end
  namespace :admin do
    resources :rails_name_methods
  end
  namespace :admin do
    resources :ruby_name_method_full_descriptions
  end
  namespace :admin do
    resources :ruby_name_methods
  end
  namespace :admin do
    resources :ruby_name_methods
  end
  namespace :admin do
    resources :ruby_name_classes
  end
  namespace :admin do
    resources :ruby_syntax_keyword_descriptions
  end
  namespace :admin do
    resources :ruby_syntax_name_keywords
  end
  namespace :admin do
    resources :ruby_syntax_name_elements
  end
  namespace :admin do
    resources :rails_name_structures
  end
  root 'static_pages#rubyhelper'

  resources :ruby_syntax

  resources :index_ruby_syntaxes

  resources :ruby_guide_methods

  resources :rails_enviroments

  devise_for :users, controllers: { registrations: 'registrations' }

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/rails_name_method.rb
class Admin::RailsNameMethod < ActiveRecord::Base
  validates :rails_name_structure_id, :name_method, presence: true
  belongs_to :admin_rails_name_structure, :class_name => 'Admin::RailsNameStructure'
end

app/models/index_ruby_syntax.rb
class IndexRubySyntax < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/rails_name_methods_controller.rb
class Admin::RailsNameMethodsController < ApplicationController
  before_action :set_admin_rails_name_method, only: [:show, :edit, :update, :destroy]

  def index
    @admin_rails_name_methods = Admin::RailsNameMethod.all
  end

  def show
  end

  def new
    @admin_rails_name_method = Admin::RailsNameMethod.new
  end

  def edit
  end

  def create
    @admin_rails_name_method = Admin::RailsNameMethod.new(admin_rails_name_method_params)
    if @admin_rails_name_method.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def update
    if @admin_rails_name_method.update(admin_rails_name_method_params)
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def destroy
    @admin_rails_name_method.destroy
    redirect_to action: :index
  end

  private
    def set_admin_rails_name_method
      @admin_rails_name_method = Admin::RailsNameMethod.find(params[:id])
    end

    def admin_rails_name_method_params
      params.require(:admin_rails_name_method).permit(:rails_name_structure_id, :name_method, :short_description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  #before_filter :update_sanitized_params, if: :devise_controller?

  #def update_sanitized_params
   # devise_parameter_sanitizer.for(:sing_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
    #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username)}
  #end

end

app/controllers/rails_enviroments_controller.rb
class RailsEnviromentsController < ApplicationController

  def index
    @rails_name_structures = Admin::RailsNameStructure.all
  end


  def show
    @rails_name_structures = Admin::RailsNameStructure.all
    @rails_name_structure = Admin::RailsNameStructure.find(params[:id])

    @name_methods = Admin::RailsNameMethod.where(rails_name_structure_id: @rails_name_structure).pluck(:id, :name_method, :short_description)

    @rails_method_descriptions = Admin::RailsMethodDescription.all
  end


  def show2
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @syntax_name_element = Admin::RubySyntaxNameElement.find(params[:id])

    @syntax_name_keywords = Admin::RubySyntaxNameKeyword.where(admin_ruby_suntax_name_element_id: @syntax_name_element).pluck(:id, :name_keyword, :name_keyword_description)
    @syntax_keyword_descriptions = Admin::RubySyntaxKeywordDescription.all
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/ruby_syntax_controller.rb
class RubySyntaxController < ApplicationController

  def index
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @index_ruby_syntaxes = IndexRubySyntax.all
  end

  def show
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @syntax_name_element = Admin::RubySyntaxNameElement.find(params[:id])

    @syntax_name_keywords = Admin::RubySyntaxNameKeyword.where(admin_ruby_suntax_name_element_id: @syntax_name_element).pluck(:id, :name_keyword, :name_keyword_description)
    @syntax_keyword_descriptions = Admin::RubySyntaxKeywordDescription.all
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def rubyhelper
  end
end

app/helpers/admin/rails_name_methods_helper.rb
module Admin::RailsNameMethodsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_name_methods_helper.rb
module ClassNameMethodsHelper
end

app/helpers/description_keywords_helper.rb
module DescriptionKeywordsHelper
end

app/helpers/index_ruby_syntaxes_helper.rb
module IndexRubySyntaxesHelper
end

app/helpers/rails_enviroments_helper.rb
module RailsEnviromentsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/ruby_guide_methods_helper.rb
module RubyGuideMethodsHelper
end

app/helpers/ruby_syntax_helper.rb
module RubySyntaxHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/syntax_elements_rubies_helper.rb
module SyntaxElementsRubiesHelper
end

app/helpers/syntax_keyword_rubies_helper.rb
module SyntaxKeywordRubiesHelper
end

app/helpers/type_inner_methods_helper.rb
module TypeInnerMethodsHelper
end

app/views/admin/rails_name_methods/_form.html.erb
<%= form_for(@admin_rails_name_method) do |f| %>
  <% if @admin_rails_name_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_rails_name_method.errors.count, "error") %> prohibited this admin_rails_name_method from being saved:</h2>

      <ul>
      <% @admin_rails_name_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="">
      <%= f.collection_select(:rails_name_structure_id, Admin::RailsNameStructure.all, :id, :name_structure, :prompt => 'Select Structure')%>
    </div>
    <br>

  <div class="field">
    <%= f.text_field :name_method, class: "form-control", placeholder: "Enter Name Method" %>
  </div>
    <br>
  <div class="field">
    <%= f.text_area :short_description, class: "form-control", placeholder: "Enter short method description" %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-default navbar-btn' %>
  </div>
<% end %>

app/views/admin/rails_name_methods/edit.html.erb
<div class="form-user">
<h4>Editing Admin Rails Name Method</h4>

<%= render 'form' %>

<%= link_to 'Show', @admin_rails_name_method %> |
<%= link_to 'Back', admin_rails_name_methods_path %>
</div>

app/views/admin/rails_name_methods/index.html.erb
<div class="form-index">
<p id="notice"><%= notice %></p>
  <div class="heading">
    <h4>Listing Admin Rails Name Methods</h4>
    | <%= link_to ' Structure ', admin_rails_name_structures_path %>
    | <%= link_to ' Rails Method description ', admin_rails_method_descriptions_path %>
    |<%= link_to ' New Rails name method ', new_admin_rails_name_method_path %> |
  </div>

  <table>
  <thead>
    <tr>
      <th>Rails name structure</th>
      <th>Name method</th>
      <th>Short description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_rails_name_methods.each do |admin_rails_name_method| %>
      <tr>
        <td><%= Admin::RailsNameStructure.find(admin_rails_name_method.rails_name_structure_id).name_structure %></td>
        <td><%= admin_rails_name_method.name_method %></td>
        <td><%= admin_rails_name_method.short_description %></td>
        <td><%= link_to 'Show', admin_rails_name_method %></td>
        <td><%= link_to 'Edit', edit_admin_rails_name_method_path(admin_rails_name_method) %></td>
        <td><%= link_to 'Destroy', admin_rails_name_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <br>
</div>

app/views/admin/rails_name_methods/new.html.erb
<div class="form-user">
  <h4>New Admin Rails Name Method</h4>
  <%= link_to 'Back', admin_rails_name_methods_path %>
  <%= render 'form' %>
</div>

app/views/admin/rails_name_methods/show.html.erb
<div class="form-user">
<p id="notice"><%= notice %></p>

<p>
  <strong>Rails name structure:</strong>
  <%= @admin_rails_name_method.rails_name_structure_id %>
</p>

<p>
  <strong>Name method:</strong>
  <%= @admin_rails_name_method.name_method %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @admin_rails_name_method.short_description %>
</p>

<%= link_to 'Edit', edit_admin_rails_name_method_path(@admin_rails_name_method) %> |
<%= link_to 'Back', admin_rails_name_methods_path %>
</div>