config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :rails_method_descriptions
  end
  namespace :admin do
    resources :rails_name_methods
  end
  namespace :admin do
    resources :ruby_name_method_full_descriptions
  end
  namespace :admin do
    resources :ruby_name_methods
  end
  namespace :admin do
    resources :ruby_name_methods
  end
  namespace :admin do
    resources :ruby_name_classes
  end
  namespace :admin do
    resources :ruby_syntax_keyword_descriptions
  end
  namespace :admin do
    resources :ruby_syntax_name_keywords
  end
  namespace :admin do
    resources :ruby_syntax_name_elements
  end
  namespace :admin do
    resources :rails_name_structures
  end
  root 'static_pages#rubyhelper'

  resources :ruby_syntax

  resources :index_ruby_syntaxes

  resources :ruby_guide_methods

  resources :rails_enviroments

  devise_for :users, controllers: { registrations: 'registrations' }

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/rails_method_description.rb
class Admin::RailsMethodDescription < ActiveRecord::Base
  validates :rails_name_method_id, presence: true
end

app/models/index_ruby_syntax.rb
class IndexRubySyntax < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/rails_method_descriptions_controller.rb
class Admin::RailsMethodDescriptionsController < ApplicationController
  before_action :set_admin_rails_method_description, only: [:show, :edit, :update, :destroy]

  def index
    @admin_rails_method_descriptions = Admin::RailsMethodDescription.all
  end

  def show
  end

  def new
    @admin_rails_method_description = Admin::RailsMethodDescription.new
  end

  def edit
  end

  def create
    @admin_rails_method_description = Admin::RailsMethodDescription.new(admin_rails_method_description_params)
    if @admin_rails_method_description.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def update
    if @admin_rails_method_description.update(admin_rails_method_description_params)
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def destroy
    @admin_rails_method_description.destroy
    redirect_to action: :index
  end

  private
    def set_admin_rails_method_description
      @admin_rails_method_description = Admin::RailsMethodDescription.find(params[:id])
    end

    def admin_rails_method_description_params
      params.require(:admin_rails_method_description).permit(:rails_name_method_id, :num_view, :lable_description, :full_method_description, :label_code, :method_code, :label_result, :result_code)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  #before_filter :update_sanitized_params, if: :devise_controller?

  #def update_sanitized_params
   # devise_parameter_sanitizer.for(:sing_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
    #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username)}
  #end

end

app/controllers/rails_enviroments_controller.rb
class RailsEnviromentsController < ApplicationController

  def index
    @rails_name_structures = Admin::RailsNameStructure.all
  end


  def show
    @rails_name_structures = Admin::RailsNameStructure.all
    @rails_name_structure = Admin::RailsNameStructure.find(params[:id])

    @name_methods = Admin::RailsNameMethod.where(rails_name_structure_id: @rails_name_structure).pluck(:id, :name_method, :short_description)

    @rails_method_descriptions = Admin::RailsMethodDescription.all
  end


  def show2
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @syntax_name_element = Admin::RubySyntaxNameElement.find(params[:id])

    @syntax_name_keywords = Admin::RubySyntaxNameKeyword.where(admin_ruby_suntax_name_element_id: @syntax_name_element).pluck(:id, :name_keyword, :name_keyword_description)
    @syntax_keyword_descriptions = Admin::RubySyntaxKeywordDescription.all
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/ruby_syntax_controller.rb
class RubySyntaxController < ApplicationController

  def index
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @index_ruby_syntaxes = IndexRubySyntax.all
  end

  def show
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @syntax_name_element = Admin::RubySyntaxNameElement.find(params[:id])

    @syntax_name_keywords = Admin::RubySyntaxNameKeyword.where(admin_ruby_suntax_name_element_id: @syntax_name_element).pluck(:id, :name_keyword, :name_keyword_description)
    @syntax_keyword_descriptions = Admin::RubySyntaxKeywordDescription.all
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def rubyhelper
  end
end

app/helpers/admin/rails_method_descriptions_helper.rb
module Admin::RailsMethodDescriptionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_name_methods_helper.rb
module ClassNameMethodsHelper
end

app/helpers/description_keywords_helper.rb
module DescriptionKeywordsHelper
end

app/helpers/index_ruby_syntaxes_helper.rb
module IndexRubySyntaxesHelper
end

app/helpers/rails_enviroments_helper.rb
module RailsEnviromentsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/ruby_guide_methods_helper.rb
module RubyGuideMethodsHelper
end

app/helpers/ruby_syntax_helper.rb
module RubySyntaxHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/syntax_elements_rubies_helper.rb
module SyntaxElementsRubiesHelper
end

app/helpers/syntax_keyword_rubies_helper.rb
module SyntaxKeywordRubiesHelper
end

app/helpers/type_inner_methods_helper.rb
module TypeInnerMethodsHelper
end

app/views/admin/rails_method_descriptions/_form.html.erb
<%= form_for(@admin_rails_method_description) do |f| %>
  <% if @admin_rails_method_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_rails_method_description.errors.count, "error") %> prohibited this admin_rails_method_description from being saved:</h2>

      <ul>
      <% @admin_rails_method_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="">
      <%= f.collection_select(:rails_name_method_id, Admin::RailsNameMethod.all, :id, :name_method, :prompt => 'Select Method')%>
    </div>
    <br>

    <div class="field">
        <%= f.number_field :num_view, class: "form-control", placeholder: "Num View" %>
    </div>
        <br>
    <div class="field">
        <%= f.text_field :lable_description, class: "form-control", placeholder: "Label Description" %>
    </div>
        <br>
    <div class="field">
        <%= f.text_area :full_method_description, class: "form-control", placeholder: "Method Description" %>
    </div>
        <br>
    <div class="field">
        <%= f.text_field :label_code, class: "form-control", placeholder: "Label Code" %>
    </div>
        <br>
    <div class="field">
        <%= f.text_area :method_code, class: "form-control", placeholder: "Example Code" %>
    </div>
        <br>
    <div class="field">
        <%= f.text_field :label_result, class: "form-control", placeholder: "Lable Result" %>
    </div>
        <br>
    <div class="">
        <%= f.text_area :result_code, class: "form-control", placeholder: "Result Code" %>
    </div>
        <br>
    <div class="actions">
        <%= f.submit 'Save', class: 'btn btn-default navbar-btn' %>
    </div>

<% end %>

app/views/admin/rails_method_descriptions/edit.html.erb
<div class="form-user">
<h4>Editing Admin Rails Method Description</h4>
  <%= render 'form' %>
  <%= link_to 'Show', @admin_rails_method_description %> |
  <%= link_to 'Back', admin_rails_method_descriptions_path %>
</div>

app/views/admin/rails_method_descriptions/index.html.erb
<div class="form-index">
<p id="notice"><%= notice %></p>

  <div class="heading">
    <h4>Listing Admin Rails Method Descriptions</h4>
    | <%= link_to ' Structure ', admin_rails_name_structures_path %>
    | <%= link_to ' Methods ', admin_rails_name_methods_path %>
    | <%= link_to ' New Rails method description ', new_admin_rails_method_description_path %> |

  </div>



  <table>
  <thead>
    <tr>
      <th>Rails name method</th>
      <th>Num view</th>
      <th>Lable description</th>
      <th>Full method description</th>
      <th>Label code</th>
      <th>Method code</th>
      <th>Label result</th>
      <th>Result code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_rails_method_descriptions.each do |admin_rails_method_description| %>
      <tr>
        <td><%= Admin::RailsNameMethod.find(admin_rails_method_description.rails_name_method_id).name_method %></td>
        <td><%= admin_rails_method_description.num_view %></td>
        <td><%= admin_rails_method_description.lable_description %></td>
        <td><%= admin_rails_method_description.full_method_description %></td>
        <td><%= admin_rails_method_description.label_code %></td>
        <td><%= admin_rails_method_description.method_code %></td>
        <td><%= admin_rails_method_description.label_result %></td>
        <td><%= admin_rails_method_description.result_code %></td>
        <td><%= link_to 'Show', admin_rails_method_description %></td>
        <td><%= link_to 'Edit', edit_admin_rails_method_description_path(admin_rails_method_description) %></td>
        <td><%= link_to 'Destroy', admin_rails_method_description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/admin/rails_method_descriptions/new.html.erb
<div class="form-user">
<h4>New Admin Rails Method Description</h4>
  <%= render 'form' %>
  <%= link_to 'Back', admin_rails_method_descriptions_path %>
</div>

app/views/admin/rails_method_descriptions/show.html.erb
<div class="form-user">
<p id="notice"><%= notice %></p>

<p>
  <strong>Rails name method:</strong>
  <%= @admin_rails_method_description.rails_name_method_id %>
</p>

<p>
  <strong>Num view:</strong>
  <%= @admin_rails_method_description.num_view %>
</p>

<p>
  <strong>Lable description:</strong>
  <%= @admin_rails_method_description.lable_description %>
</p>

<p>
  <strong>Full method description:</strong>
  <%= @admin_rails_method_description.full_method_description %>
</p>

<p>
  <strong>Label code:</strong>
  <%= @admin_rails_method_description.label_code %>
</p>

<p>
  <strong>Method code:</strong>
  <%= @admin_rails_method_description.method_code %>
</p>

<p>
  <strong>Label result:</strong>
  <%= @admin_rails_method_description.label_result %>
</p>

<p>
  <strong>Result code:</strong>
  <%= @admin_rails_method_description.result_code %>
</p>

<%= link_to 'Edit', edit_admin_rails_method_description_path(@admin_rails_method_description) %> |
<%= link_to 'Back', admin_rails_method_descriptions_path %>
</div>