config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :rails_method_descriptions
  end
  namespace :admin do
    resources :rails_name_methods
  end
  namespace :admin do
    resources :ruby_name_method_full_descriptions
  end
  namespace :admin do
    resources :ruby_name_methods
  end
  namespace :admin do
    resources :ruby_name_methods
  end
  namespace :admin do
    resources :ruby_name_classes
  end
  namespace :admin do
    resources :ruby_syntax_keyword_descriptions
  end
  namespace :admin do
    resources :ruby_syntax_name_keywords
  end
  namespace :admin do
    resources :ruby_syntax_name_elements
  end
  namespace :admin do
    resources :rails_name_structures
  end
  root 'static_pages#rubyhelper'

  resources :ruby_syntax

  resources :index_ruby_syntaxes

  resources :ruby_guide_methods

  resources :rails_enviroments

  devise_for :users, controllers: { registrations: 'registrations' }

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/index_ruby_syntax.rb
class IndexRubySyntax < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/ruby_name_classes_controller.rb
class Admin::RubyNameClassesController < ApplicationController
  before_action :set_admin_ruby_name_class, only: [:show, :edit, :update, :destroy]
  before_filter :check_if_admin, only:[:index, :show, :new, :create, :edit, :update, :delete]

  def index
    @admin_ruby_name_classes = Admin::RubyNameClass.all
  end

  def show
  end

  def new
    @admin_ruby_name_class = Admin::RubyNameClass.new
  end

  def edit
  end

  def create
    @admin_ruby_name_class = Admin::RubyNameClass.new(admin_ruby_name_class_params)
    if @admin_ruby_name_class.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def update
    if @admin_ruby_name_class.update(admin_ruby_name_class_params)
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def destroy
    @admin_ruby_name_class.destroy
    redirect_to action: :index
  end

  private
    def set_admin_ruby_name_class
      @admin_ruby_name_class = Admin::RubyNameClass.find(params[:id])
    end

    def admin_ruby_name_class_params
      params.require(:admin_ruby_name_class).permit(:num_view, :name_class)
    end

    def check_if_admin
      if current_user.role == 'superadmin'
        true
      else
        render 'static_pages/rubyhelper/'
        #render text: "Access denied "
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  #before_filter :update_sanitized_params, if: :devise_controller?

  #def update_sanitized_params
   # devise_parameter_sanitizer.for(:sing_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
    #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username)}
  #end

end

app/controllers/rails_enviroments_controller.rb
class RailsEnviromentsController < ApplicationController

  def index
    @rails_name_structures = Admin::RailsNameStructure.all
  end


  def show
    @rails_name_structures = Admin::RailsNameStructure.all
    @rails_name_structure = Admin::RailsNameStructure.find(params[:id])

    @name_methods = Admin::RailsNameMethod.where(rails_name_structure_id: @rails_name_structure).pluck(:id, :name_method, :short_description)

    @rails_method_descriptions = Admin::RailsMethodDescription.all
  end


  def show2
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @syntax_name_element = Admin::RubySyntaxNameElement.find(params[:id])

    @syntax_name_keywords = Admin::RubySyntaxNameKeyword.where(admin_ruby_suntax_name_element_id: @syntax_name_element).pluck(:id, :name_keyword, :name_keyword_description)
    @syntax_keyword_descriptions = Admin::RubySyntaxKeywordDescription.all
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/ruby_syntax_controller.rb
class RubySyntaxController < ApplicationController

  def index
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @index_ruby_syntaxes = IndexRubySyntax.all
  end

  def show
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @syntax_name_element = Admin::RubySyntaxNameElement.find(params[:id])

    @syntax_name_keywords = Admin::RubySyntaxNameKeyword.where(admin_ruby_suntax_name_element_id: @syntax_name_element).pluck(:id, :name_keyword, :name_keyword_description)
    @syntax_keyword_descriptions = Admin::RubySyntaxKeywordDescription.all
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def rubyhelper
  end
end

app/helpers/admin/ruby_name_classes_helper.rb
module Admin::RubyNameClassesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_name_methods_helper.rb
module ClassNameMethodsHelper
end

app/helpers/description_keywords_helper.rb
module DescriptionKeywordsHelper
end

app/helpers/index_ruby_syntaxes_helper.rb
module IndexRubySyntaxesHelper
end

app/helpers/rails_enviroments_helper.rb
module RailsEnviromentsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/ruby_guide_methods_helper.rb
module RubyGuideMethodsHelper
end

app/helpers/ruby_syntax_helper.rb
module RubySyntaxHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/syntax_elements_rubies_helper.rb
module SyntaxElementsRubiesHelper
end

app/helpers/syntax_keyword_rubies_helper.rb
module SyntaxKeywordRubiesHelper
end

app/helpers/type_inner_methods_helper.rb
module TypeInnerMethodsHelper
end

app/views/admin/ruby_name_classes/_form.html.erb
<%= form_for(@admin_ruby_name_class) do |f| %>
  <% if @admin_ruby_name_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_ruby_name_class.errors.count, "error") %> prohibited this admin_ruby_name_class from being saved:</h2>

      <ul>
      <% @admin_ruby_name_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= f.number_field :num_view, class: "form-control", placeholeder: "Num View" %>
  </div>
  <br>
    <div class="input-group">
    <%= f.text_field :name_class, class: "form-control", placeholeder: "Name Class" %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-default navbar-btn' %>
  </div>
<% end %>

app/views/admin/ruby_name_classes/edit.html.erb
<div class="form-user">
<h3>Editing Admin Ruby Name Class</h3>

<%= render 'form' %>

<%= link_to 'Show', @admin_ruby_name_class %> |
<%= link_to 'Back', admin_ruby_name_classes_path %>
</div>

app/views/admin/ruby_name_classes/index.html.erb
<div class="form-index">
<p id="notice"><%= notice %></p>

    <div class="heading">
        <h4>Listing Admin Ruby Name Classes</h4>
        |<%= link_to ' Methods ', admin_ruby_name_methods_path %>
        |<%= link_to ' Methods Description ', admin_ruby_name_method_full_descriptions_path %>
        |<%= link_to ' New Ruby name class ', new_admin_ruby_name_class_path %>|
    </div>

<table>
  <thead>
    <tr>
      <th>Num view</th>
      <th>Name class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_ruby_name_classes.each do |admin_ruby_name_class| %>
      <tr>
        <td><%= admin_ruby_name_class.num_view %></td>
        <td><%= admin_ruby_name_class.name_class %></td>
        <td><%= link_to 'Show', admin_ruby_name_class %></td>
        <td><%= link_to 'Edit', edit_admin_ruby_name_class_path(admin_ruby_name_class) %></td>
        <td><%= link_to 'Destroy', admin_ruby_name_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/admin/ruby_name_classes/new.html.erb
<div class="form-user">
    <h3>New Admin Ruby Name Class</h3>

    <%= render 'form' %>

    <%= link_to 'Back', admin_ruby_name_classes_path %>
</div>

app/views/admin/ruby_name_classes/show.html.erb
<div class="form-user">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Num view:</strong>
      <%= @admin_ruby_name_class.num_view %>
    </p>

    <p>
      <strong>Name class:</strong>
      <%= @admin_ruby_name_class.name_class %>
    </p>

    <%= link_to 'Edit', edit_admin_ruby_name_class_path(@admin_ruby_name_class) %> |
    <%= link_to 'Back', admin_ruby_name_classes_path %>
</div>