config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :rails_method_descriptions
  end
  namespace :admin do
    resources :rails_name_methods
  end
  namespace :admin do
    resources :ruby_name_method_full_descriptions
  end
  namespace :admin do
    resources :ruby_name_methods
  end
  namespace :admin do
    resources :ruby_name_methods
  end
  namespace :admin do
    resources :ruby_name_classes
  end
  namespace :admin do
    resources :ruby_syntax_keyword_descriptions
  end
  namespace :admin do
    resources :ruby_syntax_name_keywords
  end
  namespace :admin do
    resources :ruby_syntax_name_elements
  end
  namespace :admin do
    resources :rails_name_structures
  end
  root 'static_pages#rubyhelper'

  resources :ruby_syntax

  resources :index_ruby_syntaxes

  resources :ruby_guide_methods

  resources :rails_enviroments

  devise_for :users, controllers: { registrations: 'registrations' }

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/ruby_name_method_full_description.rb
class Admin::RubyNameMethodFullDescription < ActiveRecord::Base
  validates :ruby_name_method_id, presence: true
end

app/models/index_ruby_syntax.rb
class IndexRubySyntax < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/ruby_name_method_full_descriptions_controller.rb
class Admin::RubyNameMethodFullDescriptionsController < ApplicationController
  before_action :set_admin_ruby_name_method_full_description, only: [:show, :edit, :update, :destroy]

  # GET /admin/ruby_name_method_full_descriptions
  # GET /admin/ruby_name_method_full_descriptions.json
  def index
    @admin_ruby_name_method_full_descriptions = Admin::RubyNameMethodFullDescription.all
  end

  # GET /admin/ruby_name_method_full_descriptions/1
  # GET /admin/ruby_name_method_full_descriptions/1.json
  def show
  end

  # GET /admin/ruby_name_method_full_descriptions/new
  def new
    @admin_ruby_name_method_full_description = Admin::RubyNameMethodFullDescription.new
  end

  # GET /admin/ruby_name_method_full_descriptions/1/edit
  def edit
  end

  # POST /admin/ruby_name_method_full_descriptions
  # POST /admin/ruby_name_method_full_descriptions.json
  def create
    @admin_ruby_name_method_full_description = Admin::RubyNameMethodFullDescription.new(admin_ruby_name_method_full_description_params)

    respond_to do |format|
      if @admin_ruby_name_method_full_description.save
        format.html { redirect_to @admin_ruby_name_method_full_description, notice: 'Ruby name method full description was successfully created.' }
        format.json { render :show, status: :created, location: @admin_ruby_name_method_full_description }
      else
        format.html { render :new }
        format.json { render json: @admin_ruby_name_method_full_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/ruby_name_method_full_descriptions/1
  # PATCH/PUT /admin/ruby_name_method_full_descriptions/1.json
  def update
    respond_to do |format|
      if @admin_ruby_name_method_full_description.update(admin_ruby_name_method_full_description_params)
        format.html { redirect_to @admin_ruby_name_method_full_description, notice: 'Ruby name method full description was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_ruby_name_method_full_description }
      else
        format.html { render :edit }
        format.json { render json: @admin_ruby_name_method_full_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/ruby_name_method_full_descriptions/1
  # DELETE /admin/ruby_name_method_full_descriptions/1.json
  def destroy
    @admin_ruby_name_method_full_description.destroy
    respond_to do |format|
      format.html { redirect_to admin_ruby_name_method_full_descriptions_url, notice: 'Ruby name method full description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_ruby_name_method_full_description
      @admin_ruby_name_method_full_description = Admin::RubyNameMethodFullDescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_ruby_name_method_full_description_params
      params.require(:admin_ruby_name_method_full_description).permit(:ruby_name_method_id, :num_view, :label_description, :full_method_description, :label_code, :method_code, :label_result, :result_code)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  #before_filter :update_sanitized_params, if: :devise_controller?

  #def update_sanitized_params
   # devise_parameter_sanitizer.for(:sing_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
    #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username)}
  #end

end

app/controllers/rails_enviroments_controller.rb
class RailsEnviromentsController < ApplicationController

  def index
    @rails_name_structures = Admin::RailsNameStructure.all
  end


  def show
    @rails_name_structures = Admin::RailsNameStructure.all
    @rails_name_structure = Admin::RailsNameStructure.find(params[:id])

    @name_methods = Admin::RailsNameMethod.where(rails_name_structure_id: @rails_name_structure).pluck(:id, :name_method, :short_description)

    @rails_method_descriptions = Admin::RailsMethodDescription.all
  end


  def show2
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @syntax_name_element = Admin::RubySyntaxNameElement.find(params[:id])

    @syntax_name_keywords = Admin::RubySyntaxNameKeyword.where(admin_ruby_suntax_name_element_id: @syntax_name_element).pluck(:id, :name_keyword, :name_keyword_description)
    @syntax_keyword_descriptions = Admin::RubySyntaxKeywordDescription.all
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/ruby_syntax_controller.rb
class RubySyntaxController < ApplicationController

  def index
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @index_ruby_syntaxes = IndexRubySyntax.all
  end

  def show
    @syntax_name_elements = Admin::RubySyntaxNameElement.all
    @syntax_name_element = Admin::RubySyntaxNameElement.find(params[:id])

    @syntax_name_keywords = Admin::RubySyntaxNameKeyword.where(admin_ruby_suntax_name_element_id: @syntax_name_element).pluck(:id, :name_keyword, :name_keyword_description)
    @syntax_keyword_descriptions = Admin::RubySyntaxKeywordDescription.all
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def rubyhelper
  end
end

app/helpers/admin/ruby_name_method_full_descriptions_helper.rb
module Admin::RubyNameMethodFullDescriptionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_name_methods_helper.rb
module ClassNameMethodsHelper
end

app/helpers/description_keywords_helper.rb
module DescriptionKeywordsHelper
end

app/helpers/index_ruby_syntaxes_helper.rb
module IndexRubySyntaxesHelper
end

app/helpers/rails_enviroments_helper.rb
module RailsEnviromentsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/ruby_guide_methods_helper.rb
module RubyGuideMethodsHelper
end

app/helpers/ruby_syntax_helper.rb
module RubySyntaxHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/syntax_elements_rubies_helper.rb
module SyntaxElementsRubiesHelper
end

app/helpers/syntax_keyword_rubies_helper.rb
module SyntaxKeywordRubiesHelper
end

app/helpers/type_inner_methods_helper.rb
module TypeInnerMethodsHelper
end

app/views/admin/ruby_name_method_full_descriptions/_form.html.erb
<%= form_for(@admin_ruby_name_method_full_description) do |f| %>
  <% if @admin_ruby_name_method_full_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_ruby_name_method_full_description.errors.count, "error") %> prohibited this admin_ruby_name_method_full_description from being saved:</h2>

      <ul>
      <% @admin_ruby_name_method_full_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="">
      <%= f.collection_select(:ruby_name_method_id, Admin::RubyNameMethod.all, :id, :name_method, :prompt => 'Select Method')%>
    </div>
    <br>

  <div class="">
    <%= f.number_field :num_view, class: "form-control", placeholder: "Num View" %>
  </div>
    <br>
  <div class="">
    <%= f.text_field :label_description, class: "form-control", placeholder: "Label Description" %>
  </div>
    <br>
  <div class="">
    <%= f.text_area :full_method_description, class: "form-control", placeholder: "Method Description" %>
  </div>
    <br>
  <div class="">
    <%= f.text_field :label_code, class: "form-control", placeholder: "Label Code" %>
  </div>
    <br>
  <div class="">
    <%= f.text_area :method_code, class: "form-control", placeholder: "Example Code" %>
  </div>
    <br>
  <div class="">
    <%= f.text_field :label_result, class: "form-control", placeholder: "Lable Result" %>
  </div>
    <br>
  <div class="">
    <%= f.text_area :result_code, class: "form-control", placeholder: "Result Code" %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-default navbar-btn'%>
  </div>
<% end %>

app/views/admin/ruby_name_method_full_descriptions/edit.html.erb
<div class="form-user">
<h4>Editing Admin Ruby Name Method Full Description</h4>

<%= render 'form' %>

<%= link_to 'Show', @admin_ruby_name_method_full_description %> |
<%= link_to 'Back', admin_ruby_name_method_full_descriptions_path %>
</div>

app/views/admin/ruby_name_method_full_descriptions/index.html.erb
<div class="form-index">
<p id="notice"><%= notice %></p>

    <div class="heading">
      <h4>Listing Admin Ruby Name Method Full Descriptions</h4>
      | <%= link_to ' Classes ', admin_ruby_name_classes_path %>
      | <%= link_to ' Methods ', admin_ruby_name_methods_path %>
      | <%= link_to ' New Ruby name method full description ', new_admin_ruby_name_method_full_description_path %> |
    </div>

  <table>
  <thead>
    <tr>
      <th>Ruby name method</th>
      <th>Num view</th>
      <th>Label description</th>
      <th>Full method description</th>
      <th>Label code</th>
      <th>Method code</th>
      <th>Label result</th>
      <th>Result code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_ruby_name_method_full_descriptions.each do |admin_ruby_name_method_full_description| %>
      <tr>
        <td><%= Admin::RubyNameMethod.find(admin_ruby_name_method_full_description.ruby_name_method_id).name_method%></td>
        <td><%= admin_ruby_name_method_full_description.num_view %></td>
        <td><%= admin_ruby_name_method_full_description.label_description %></td>
        <td><%= admin_ruby_name_method_full_description.full_method_description %></td>
        <td><%= admin_ruby_name_method_full_description.label_code %></td>
        <td><%= admin_ruby_name_method_full_description.method_code %></td>
        <td><%= admin_ruby_name_method_full_description.label_result %></td>
        <td><%= admin_ruby_name_method_full_description.result_code %></td>
        <td><%= link_to 'Show', admin_ruby_name_method_full_description %></td>
        <td><%= link_to 'Edit', edit_admin_ruby_name_method_full_description_path(admin_ruby_name_method_full_description) %></td>
        <td><%= link_to 'Destroy', admin_ruby_name_method_full_description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/admin/ruby_name_method_full_descriptions/new.html.erb
<div class="form-user">
<h4>New Admin Ruby Name Method Full Description</h4>

<%= render 'form' %>

<%= link_to 'Back', admin_ruby_name_method_full_descriptions_path %>
</div>

app/views/admin/ruby_name_method_full_descriptions/show.html.erb
<div class="form-user">
<p id="notice"><%= notice %></p>

<p>
  <strong>Ruby name method:</strong>
  <%= @admin_ruby_name_method_full_description.ruby_name_method_id %>
</p>

<p>
  <strong>Num view:</strong>
  <%= @admin_ruby_name_method_full_description.num_view %>
</p>

<p>
  <strong>Label description:</strong>
  <%= @admin_ruby_name_method_full_description.label_description %>
</p>

<p>
  <strong>Full method description:</strong>
  <%= @admin_ruby_name_method_full_description.full_method_description %>
</p>

<p>
  <strong>Label code:</strong>
  <%= @admin_ruby_name_method_full_description.label_code %>
</p>

<p>
  <strong>Method code:</strong>
  <%= @admin_ruby_name_method_full_description.method_code %>
</p>

<p>
  <strong>Label result:</strong>
  <%= @admin_ruby_name_method_full_description.label_result %>
</p>

<p>
  <strong>Result code:</strong>
  <%= @admin_ruby_name_method_full_description.result_code %>
</p>

<%= link_to 'Edit', edit_admin_ruby_name_method_full_description_path(@admin_ruby_name_method_full_description) %> |
<%= link_to 'Back', admin_ruby_name_method_full_descriptions_path %>
</div>